---
on:
  push:
    branches:
      - "main"
  pull_request:
name: Test
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - name: Check out source
        uses: actions/checkout@v3

      - name: Install Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24.2"
          elixir-version: "1.13.4"

      - name: Check formatting
        run: mix format --check-formatted

      - name: Retrieve cached dependencies
        id: mix-cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compile code
        run: |
          mix compile --warnings-as-errors

      - name: Run tests
        run: mix test

      - name: Run static code analysis tools
        run: | 
          mix credo
          mix deps.audit
          mix dialyzer --format github
